//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuddySystem
    {
        public int IdBuddy { get; set; }
        public int IdDiveLog { get; set; }
        public string BuddyName { get; set; }
        public string CertificationLevel { get; set; }
        public string ContactDetails { get; set; }
    
        public virtual DiveLogs DiveLogs { get; set; }
    }
}
