//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuddySystem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BuddySystem()
        {
            this.DiveLogs = new HashSet<DiveLogs>();
        }
    
        public int IdBuddy { get; set; }
        public string BuddyFirstName { get; set; }
        public string BuddyLastName { get; set; }
        public string CertificationLevel { get; set; }
        public string ContactDetails { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiveLogs> DiveLogs { get; set; }
    }
}
