//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificates
    {
        public int IdCertificate { get; set; }
        public int IdUser { get; set; }
        public int IdOrganization { get; set; }
        public int IdTypeOfTraining { get; set; }
        public System.DateTime IssueDate { get; set; }
        public string CertificateNumber { get; set; }
    
        public virtual CertificationOrganization CertificationOrganization { get; set; }
        public virtual TypeOfTraining TypeOfTraining { get; set; }
        public virtual User User { get; set; }
    }
}
