//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiveStatistic
    {
        public int IdStatistic { get; set; }
        public int IdDiveLog { get; set; }
        public Nullable<decimal> AirConsumed { get; set; }
        public Nullable<decimal> AscentRate { get; set; }
        public Nullable<int> BottomTime { get; set; }
    
        public virtual DiveLogs DiveLogs { get; set; }
    }
}
