//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiveConditions
    {
        public int IdCondition { get; set; }
        public int IdDiveLog { get; set; }
        public decimal Temperature { get; set; }
        public string WaterCurrent { get; set; }
        public string Visibility { get; set; }
        public string Notes { get; set; }
    
        public virtual DiveLogs DiveLogs { get; set; }
    }
}
