//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiveLogs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DiveLogs()
        {
            this.BuddySystem = new HashSet<BuddySystem>();
            this.DiveConditions = new HashSet<DiveConditions>();
            this.DiveStatistic = new HashSet<DiveStatistic>();
        }
    
        public int IdDiveLog { get; set; }
        public int IdUser { get; set; }
        public int IdDiveType { get; set; }
        public int IdDiveSite { get; set; }
        public System.DateTime DiveDate { get; set; }
        public int DiveDuration { get; set; }
        public decimal MaxDepth { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuddySystem> BuddySystem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiveConditions> DiveConditions { get; set; }
        public virtual DiveTypes DiveTypes { get; set; }
        public virtual DiveSites DiveSites { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiveStatistic> DiveStatistic { get; set; }
    }
}
