//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.MaintenanceSchedule = new HashSet<MaintenanceSchedule>();
        }
    
        public int IdEquipment { get; set; }
        public int IdCategory { get; set; }
        public int IdManufacturer { get; set; }
        public string Name { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
    
        public virtual EquipmentCategories EquipmentCategories { get; set; }
        public virtual EquipmentManufacturer EquipmentManufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceSchedule> MaintenanceSchedule { get; set; }
    }
}
