//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceSchedule
    {
        public int IdMaintenanceSchedule { get; set; }
        public int IdEquipment { get; set; }
        public System.DateTime ScheduledDate { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
    
        public virtual Equipment Equipment { get; set; }
    }
}
